name: SQL Linter
on:
  push:
    branches: 
      - main

jobs:
  SQLLinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3
      
      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Run SQL Linter
        run: sqlfluff lint "$GITHUB_WORKSPACE/SoftWareProductDevelopment/2-SoftwareDesign/2.5-DataLinter/DataSchemaModified.sql" --dialect postgres
